sudo: required
services:
    - docker

script:
    - docker build -t terrydesigns/node .
    - docker images terrydesigns/node 

# before_deploy:
#     - docker login -u username -p password

# deploy:
#     provider: script
#     script: docker push terrydesigns/node
#     on:
#         branch: master